AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  myChatbot:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      Handler: index.handler
      MemorySize: 3008
      Role: 'arn:aws:iam::468252701278:role/service-role/myChatbot-role-kaxuvrev'
      Runtime: nodejs8.10
      Timeout: 3
